# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gitlk',
            field=models.URLField(default='nofile'),
        ),
    ]
