# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_gitlk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gitlk',
        ),
    ]
