# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-12 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_gitlk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.FileField(default='nofile', help_text='.py or .c or .cpp or .java', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.FileField(default='nofile', help_text='.doc or .pdf or .txt', upload_to=''),
        ),
    ]
