# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-12 11:06
from __future__ import unicode_literals

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200712_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.FileField(default='nofile', upload_to='', validators=[blog.validators.validate_file_extension]),
        ),
    ]
