# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-12 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200712_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.FileField(default='nofile', upload_to=''),
        ),
    ]
